### PR TITLE
Add coverage for Ubuntu 18.04 and 20.04

### PR DESCRIPTION
**Pull request by sbesson**
Supersedes https://github.com/ome/ansible-example-omero-onenode/pull/8

- cherry-picks the relevant commits adding a new Molecule Ubuntu 18.04 scenario
- adds an Ubuntu 20.04 scenario 
- bumps `ome.omero_server` and `ome.omero_web` to the latest versions adding support to Ubuntu 20.04 (thanks to @stephenogg)

### CODE REVIEW

**Comment by joshmoore** [comment]
Primary question is why there's a dedicated `test_ubuntu.py` script.

**Comment by sbesson** [comment]
> Primary question is why there's a dedicated test_ubuntu.py script.

My understanding is that these are the divergences

```diff
sbesson@ls30630:ansible-example-omero-onenode (ubuntu) $ diff molecule/centos7/tests/test_default.py molecule/ubuntu2004/tests/test_ubuntu.py 
3c3
< from time import sleep
---
> from time import sleep, time
14c14
<     service = host.service('postgresql-11')
---
>     service = host.service('postgresql@11-main')
25a26,27
>     # Ubuntu sudo doesn't set HOME so it tries to write to /root
>     env = 'OMERO_USERDIR=/tmp/omero-{}'.format(time())
28c30
<             '%s login -C -s localhost -u root -w ChangeMe' % OMERO)
---
>             '%s %s login -C -s localhost -u root -w ChangeMe' % (env, OMERO))
```

There's two main diff: the service name is different and the default `OMERO_USERDIR`. I was debating trying to unify and try to use groups or distribution parsing to handle the OS specificities.

While discussing unifications, another discrepancy is

```diff
sbesson@ls30630:ansible-example-omero-onenode (ubuntu) $ diff playbook.yml playbook-ubuntu.yml 
12a13
>       omero_server_selfsigned_certificates: true
14a16
>     ansible_python_interpreter: /usr/bin/python3
```

I assume `omero_server_selfsigned_certificates` could be set to `true` across the board but I think the `ansible_python_interpreter` might be Ubuntu-specific (since `python3` is not installed by default)

**Comment by sbesson** [comment]
@joshmoore the last commits should unify the playbook (and fetch Ubuntu-specific variables) as well as the tests for all supported platforms.

**Review by joshmoore — APPROVED** [review]
Wow. Thanks for humoring me.

**Comment by sbesson** [comment]
> Wow. Thanks for humoring me.

No worries. The comment was far from being unreasonable and I think overall this helps us with testing our playbooks across multiple platforms. At least from my side, learning about `host.systeminfo` was handy to handle OS-specific behavior in `pytest/testinfra`.

If no objection, I'll look into re-using a similar template for the other Ansible examples and cover CentOS 7/Ubuntu 18.04/Ubuntu 20.04 across the board

**Pull request merged**
